name: portfolio
description: This page describes the unheard saga of a Flutter developer who is passionate about his work!.

publish_to: 'none' 

version: 1.1.0+2

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  flutter_svg: ^1.1.1+1
  flutter_riverpod: ^1.0.4
  url_launcher: ^6.1.5
  firebase_core: ^2.13.0
  firebase_analytics: ^10.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
  fonts:
    - family: roboto
      fonts:
        - asset: assets/fonts/RobotoCondensed-Light.ttf
          weight: 300
        - asset: assets/fonts/RobotoCondensed-Regular.ttf
          weight: 500
        - asset: assets/fonts/RobotoCondensed-Bold.ttf
          weight: 700
