// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYwFLL03GC7ZtboI6ZYaVPfsc3IMG_PT0',
    appId: '1:22155030320:web:cbbdfeb491bc621612e2f5',
    messagingSenderId: '22155030320',
    projectId: 'portfolio-4c282',
    authDomain: 'portfolio-4c282.firebaseapp.com',
    storageBucket: 'portfolio-4c282.appspot.com',
    measurementId: 'G-EWDR1EXQ73',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCI0fim5wCGUkl0LPtkOYTUGO9OAqYbSYM',
    appId: '1:22155030320:android:0281a6aa31004e4912e2f5',
    messagingSenderId: '22155030320',
    projectId: 'portfolio-4c282',
    storageBucket: 'portfolio-4c282.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVevFXcACTq1UybDHlkYBYyzXgKJJZmTg',
    appId: '1:22155030320:ios:8e17c9785c7d33f612e2f5',
    messagingSenderId: '22155030320',
    projectId: 'portfolio-4c282',
    storageBucket: 'portfolio-4c282.appspot.com',
    iosClientId: '22155030320-ls1dsid29mke6k54j4sshsotoah0ve71.apps.googleusercontent.com',
    iosBundleId: 'com.example.portfolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVevFXcACTq1UybDHlkYBYyzXgKJJZmTg',
    appId: '1:22155030320:ios:8e17c9785c7d33f612e2f5',
    messagingSenderId: '22155030320',
    projectId: 'portfolio-4c282',
    storageBucket: 'portfolio-4c282.appspot.com',
    iosClientId: '22155030320-ls1dsid29mke6k54j4sshsotoah0ve71.apps.googleusercontent.com',
    iosBundleId: 'com.example.portfolio',
  );
}
